/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <>
      <div className="div">
        <div className="div-2">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e943a1d7-e6cd-45ea-b413-17ee2bf6d8e9?apiKey=3c46c17ca0b44d2fbe01abd8f47d7f7e&"
            className="img"
          />
          <div className="div-3">
            <div className="div-4">
              <div className="div-5">Career</div>
              <div className="div-6">Blogs</div>
              <div className="div-7">Leaderboard</div>
              <div className="div-8">Fees</div>
            </div>
            <div className="div-9">Trade Now</div>
          </div>
        </div>
      </div>
      <style jsx>{`
        .div {
          justify-content: center;
          align-items: center;
          align-self: stretch;
          border-bottom: 1px solid rgba(255, 255, 255, 0);
          backdrop-filter: blur(20px);
          background-color: rgba(0, 0, 0, 1);
          display: flex;
          flex-direction: column;
          padding: 0 20px;
        }
        .div-2 {
          display: flex;
          width: 100%;
          max-width: 1006px;
          align-items: center;
          justify-content: space-between;
          gap: 20px;
          margin: 24px 0 24px 40px;
        }
        @media (max-width: 991px) {
          .div-2 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .img {
          aspect-ratio: 4.17;
          object-fit: contain;
          object-position: center;
          width: 100px;
          overflow: hidden;
          max-width: 100%;
          margin: auto 0;
        }
        .div-3 {
          justify-content: space-between;
          align-items: center;
          align-self: stretch;
          display: flex;
          gap: 20px;
        }
        @media (max-width: 991px) {
          .div-3 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .div-4 {
          display: flex;
          justify-content: space-between;
          gap: 20px;
          margin: auto 0;
        }
        @media (max-width: 991px) {
          .div-4 {
            justify-content: center;
          }
        }
        .div-5 {
          color: #fcfcfc;
          font: 400 14px/17px Neurial Grotesk, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        .div-6 {
          color: #fcfcfc;
          font: 400 14px/17px Neurial Grotesk, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        .div-7 {
          color: #fcfcfc;
          font: 400 14px/17px Neurial Grotesk, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        .div-8 {
          color: #fcfcfc;
          white-space: nowrap;
          font: 400 14px/17px Neurial Grotesk, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        @media (max-width: 991px) {
          .div-8 {
            white-space: initial;
          }
        }
        .div-9 {
          color: #000;
          text-transform: uppercase;
          white-space: nowrap;
          justify-content: center;
          align-items: center;
          border-radius: 8px;
          background: linear-gradient(86deg, #d4f938 23.09%, #32d875 108.69%);
          box-shadow: 0px 0px 16px 0px rgba(168, 239, 156, 0.8);
          backdrop-filter: blur(5px);
          align-self: stretch;
          flex-grow: 1;
          padding: 15px 20px;
          font: 700 16px/19px Neurial Grotesk, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        @media (max-width: 991px) {
          .div-9 {
            white-space: initial;
          }
        }
      `}</style>
    </>
  );
}
